# all-features = true
# features = []

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
]

[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Unicode-DFS-2016",
  # "ISC",
  # "MPL-2.0",
  # "BSD-2-Clause",
  # "BSD-3-Clause",
  # "OpenSSL",
  # "CC0-1.0",
  # "Unlicense",
  # "Zlib",
  # "Unicode-3.0",
]
confidence-threshold = 0.8
exceptions = []

[licenses.private]
ignore = true

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

[bans]
multiple-versions = "allow"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
# eg { name = "ansi_term", version = "=0.11.0" },
allow = []
deny = []
# Certain crates/versions that will be skipped when doing duplicate detection.
skip = []
# Similarly to `skip` allows you to skip certain crates during duplicate
# detection. Unlike skip, it also includes the entire tree of transitive
# dependencies starting at the specified crate, up to a certain depth, which is
# by default infinite.
# eg { name = "ansi_term", version = "=0.11.0", depth = 20 },
skip-tree = []
